-- require the configs
require("plugins.config.lspconfig")
require("plugins.config.lualine")
require("plugins.config.colorizer")
require("plugins.config.telescope")
require("plugins.config.cmp")
require("plugins.config.treesitter")
require("plugins.config.tree")
require("plugins.config.toggleterm")
require("plugins.config.comment")
