
[zsh.files]
zshrc = "~/.zshrc"
zshenv = "~/.zshenv"
"zsh" = "~/.config/zsh"

[alacritty.files]
alacritty = "~/.config/alacritty/alacritty.yml"

[vim.files]
vim_init = "~/.config/nvim/init.vim"
nvim_luaconfig = "~/.config/nvim/lua/config.lua"

[nvim_lua.files]
"lua_vim" = "~/.config/nvim"

[git.files]
gitconfig = "~/.gitconfig"
gitignore = "~/.gitignore"

[desktop.files]
rofi = "~/.config/rofi/config.rasi"
rofi_theme = "~/.local/share/rofi/themes/base16-gruvbox-dark-medium.rasi"
leftwm = "~/.config/leftwm/config.toml"
