
[zsh.files]
zshrc = "~/.zshrc"
zshenv = "~/.zshenv"
"zsh" = "~/.config/zsh"

[alacritty.files]
alacritty = "~/.config/alacritty/alacritty.yml"

[git.files]
gitconfig = "~/.gitconfig"
gitignore = "~/.gitignore"

[desktop.files]
"config" = { target = "~/.config", type = "symbolic" }
"config/alacritty" = { target = "~/.config/alacritty", type = "template" }
"config/spotifyd" = { target = "~/.config/spotifyd", type = "template" }
"config/spotify-player" = { target = "~/.config/spotify-player", type = "template" }

rofi_theme = "~/.local/share/rofi/themes/base16-gruvbox-dark-medium.rasi"
latexmkrc = "~/.latexmkrc"

[pirating.files]
"pirating/.env" = { target = "~/pirating/.env", type = "template" }
"pirating/docker-compose.yml" = { target = "~/pirating/docker-compose.yml", type = "symbolic" }

[aws.files]
aws = "~/.aws"

[mwt.files]
"mwt/zsh" = "~/.config/zsh"
