
[zsh.files]
zshrc = "~/.zshrc"
zshenv = "~/.zshenv"
"zsh" = "~/.config/zsh"

[alacritty.files]
alacritty = "~/.config/alacritty/alacritty.yml"

[git.files]
gitconfig = "~/.gitconfig"
gitignore = "~/.gitignore"

[desktop.files]
"config" = "~/.config"
# "config/spotifyd/spotifyd.conf" = "~/.config/spotifyd/spotifyd.conf"
rofi_theme = "~/.local/share/rofi/themes/base16-gruvbox-dark-medium.rasi"

[pirating.files]
"pirating" = "~/pirating"

[aws.files]
aws = "~/.aws"
