
[zsh.files]
zshrc = "~/.zshrc"
zshenv = "~/.zshenv"
"zsh" = "~/.config/zsh"

[alacritty.files]
alacritty = "~/.config/alacritty/alacritty.yml"

[nvim.files]
nvim = { target = "~/.config/nvim", type = "symbolic" }

[git.files]
gitconfig = "~/.gitconfig"
gitignore = "~/.gitignore"

[desktop.files]
rofi = "~/.config/rofi/config.rasi"
rofi_theme = "~/.local/share/rofi/themes/base16-gruvbox-dark-medium.rasi"
leftwm = "~/.config/leftwm/config.toml"

[pirating.files]
"pirating" = "~/pirating"
